# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TimeField()),
                ('last_pool_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField()),
                ('addr', models.IntegerField()),
                ('reg', models.IntegerField()),
                ('valid', models.IntegerField()),
                ('last_pool_time', models.IntegerField()),
                ('counter_error', models.IntegerField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mb_server.Period')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mb_server.Port')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.IntegerField()),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ValueFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('comment', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='value',
            name='flag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mb_server.ValueFlag'),
        ),
        migrations.AddField(
            model_name='value',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mb_server.Register'),
        ),
    ]
