# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'verbose_name': 'Период', 'verbose_name_plural': 'Периоды'},
        ),
        migrations.AlterModelOptions(
            name='port',
            options={'verbose_name': 'Порт', 'verbose_name_plural': 'Порты'},
        ),
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': 'Регистер', 'verbose_name_plural': 'Регистры'},
        ),
        migrations.AlterField(
            model_name='register',
            name='counter_error',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='last_pool_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='valid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
