# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb_server', '0002_auto_20171007_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valueflag',
            options={'verbose_name': 'Статус флага результата', 'verbose_name_plural': 'Статусы флага результата'},
        ),
        migrations.AlterField(
            model_name='register',
            name='enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='value',
            name='flag',
            field=models.CharField(choices=[('GOOD', 'Good'), ('TOUT', 'Time Out'), ('ERR', 'Error')], max_length=4),
        ),
    ]
