# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mb_server', '0003_auto_20171007_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='last_pool_time',
            new_name='last_poll_second',
        ),
    ]
