# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mb_server', '0004_auto_20171008_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='value',
            options={'verbose_name': 'Значение', 'verbose_name_plural': 'Значения'},
        ),
    ]
