# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 20:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mb_server', '0005_auto_20171009_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeStamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Value2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(choices=[('GOOD', 'Good'), ('TOUT', 'Time Out'), ('ERR', 'Error')], max_length=4)),
                ('value', django.contrib.postgres.fields.jsonb.JSONField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mb_server.Date')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mb_server.Register')),
                ('time_stamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mb_server.TimeStamp')),
            ],
            options={
                'verbose_name': 'Значение2',
                'verbose_name_plural': 'Значения2',
            },
        ),
    ]
