# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb_server', '0006_date_timestamp_value2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='date',
            options={'verbose_name': 'Дата', 'verbose_name_plural': 'Даты'},
        ),
        migrations.AlterModelOptions(
            name='timestamp',
            options={'verbose_name': 'Штамп времени', 'verbose_name_plural': 'Штампы времени'},
        ),
        migrations.AddField(
            model_name='timestamp',
            name='title',
            field=models.CharField(default='null', max_length=40),
            preserve_default=False,
        ),
    ]
