# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mb_server', '0008_auto_20171103_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='last_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registers', to='mb_server.Device'),
        ),
    ]
