# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb_server', '0009_auto_20171108_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='last_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
